# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: Docker@2
  displayName: Docker Build
  inputs:
    containerRegistry: 'DigitalOcean-Registry'
    repository: 'willlianromao-k8s-demo'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: CmdLine@2
  inputs:
    script: 'docker login -u 957b3d4b151b9c342ed6e4041cdc724002da2b28f547c9f23333ca1e5032ee47 -p 957b3d4b151b9c342ed6e4041cdc724002da2b28f547c9f23333ca1e5032ee47 registry.digitalocean.com'
- task: Docker@2
  displayName: Docker Push
  inputs:
    containerRegistry: 'DigitalOcean-Registry'
    repository: 'willlianromao-k8s-demo'
    command: 'push'